# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09383df514f95bb0c609fde9da839ec57fb389e4f2a3edbe726db9bb8014fe40c38945682fe50c906593156bfe29874f3d9ff44cd00b72e9c048aeac82997c27

test:
  secret_key_base: 14559740072483844270942eccccf975eca4d759662fbfab4248354a976f5055428002e59716d19a57c8e208dfc63b790496d9b03a261cc70bb04d4b667855d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
